name: "Adoption Tracking"

on:
  push:
    branches: [main]

jobs:
  track-package:
    name: Track package version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24.13.0

      - name: Install dependencies
        run: npm ci

      - name: Track package with Zeroheight
        env:
          ZEROHEIGHT_CLIENT_ID: ${{ secrets.ZEROHEIGHT_CLIENT_ID }}
          ZEROHEIGHT_ACCESS_TOKEN: ${{ secrets.ZEROHEIGHT_ACCESS_TOKEN }}
        run: npx @zeroheight/adoption-cli track-package --interactive false -p "@castui/cast-ui"
